In [1]:
# Installing Numpy
!pip install numpy


## Getting started with Numpy..
- understand numpy
- create arrays
- information retrieval using slicing and indexing
- learn basic operations
- test numpy skills with exercises
-  


In [2]:
import numpy as np 
# a python library for creating N-dimension arrays.

In [3]:
print(np.__version__)

1.26.2


### Numpy arrays

In [4]:
mylist = [2.4,6,8,9]
mylist 


[2.4, 6, 8, 9]

In [5]:
# converting a list to a numpy array
myarray = np.array(mylist)
type(myarray)

numpy.ndarray

In [6]:
mymatrix = [[1,2,3], [4,5,6], [6,7,8]]
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
# creating our own array

np.arange(0,200,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195])

In [10]:
# creatind a large matrix of zeros 
np.zeros(5) # single array 

array([0., 0., 0., 0., 0.])

In [11]:
# creating matrices using tuples (rows, columns)
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((4,4)) # similar to np.zeros

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# using a linspace function - returns evenly spaced numbers over a specified interval 
# (starting_point, stop_point, how many numbers we want)

np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [17]:
#  using an eye function - np.eye for creating an identity matrix 

np.eye(5)



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Creating random distributions of Data

In [24]:
np.random.rand(1) # random numbers with uniform distributions 


array([0.63868833])

In [27]:
np.random.randn(1)

array([-1.3241023])

In [26]:

#passing in a shape of the required data.
np.random.randn(4,5)

array([[ 0.02533831, -1.44588947, -0.47252481, -2.74506345, -0.11243806],
       [-1.73225962,  0.39511199, -0.51146218,  1.10378224, -0.26478742],
       [-0.19339885, -1.32941882,  0.61727739,  1.76768154, -0.09328811],
       [ 0.1562013 , -0.81996362,  0.38285679, -0.84870965, -0.54851341]])

In [28]:
np.random.randint(0,101,5)

array([77,  0, 11, 39, 94])

In [29]:
np.random.randint(0,101,(4,6))

array([[48,  6,  0,  5, 21, 11],
       [30,  7, 25, 66, 15, 42],
       [29, 63, 91, 41, 78, 50],
       [58,  6, 88, 76, 44, 73]])

In [33]:
# choosing a seed
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [39]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

###
- Max
- Min
- Argmax
- Argmin


In [44]:
random_arr = np.random.randint(0,101, 9)
random_arr


array([32, 75, 57, 21, 88, 48, 90, 58, 41])

In [47]:
random_arr.max()


90

In [46]:
random_arr.min()

21

In [49]:
random_arr.argmin()

3

In [50]:
random_arr.dtype

dtype('int32')

In [51]:
random_arr.shape


(9,)

In [54]:
arr = random_arr.reshape(3,3)

In [55]:
arr.shape 

(3, 3)

In [56]:
arr

array([[32, 75, 57],
       [21, 88, 48],
       [90, 58, 41]])

# Indexing and selections in Numpy

In [57]:
arr 

array([[32, 75, 57],
       [21, 88, 48],
       [90, 58, 41]])

In [58]:
random_arr

array([32, 75, 57, 21, 88, 48, 90, 58, 41])

In [59]:
#Using random_arr

len(random_arr)

9

In [60]:
random_arr[8]

41

In [61]:
random_arr[2:6]

array([57, 21, 88, 48])

In [62]:
random_arr[:]  # start from first to last element in the array

array([32, 75, 57, 21, 88, 48, 90, 58, 41])

### Rebroadcasting 

In [63]:
random_arr

array([32, 75, 57, 21, 88, 48, 90, 58, 41])

In [64]:
random_arr[2:5] = 100

In [65]:
random_arr

array([ 32,  75, 100, 100, 100,  48,  90,  58,  41])

In [66]:
slice_of_arr = random_arr[2:5]
slice_of_arr

array([100, 100, 100])

# Creating 2D arrays 

In [68]:
arr_2d = np.array([[5,10,15],[20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr_2d.shape

(3, 3)

In [72]:
arr_2d[2, 1]

40

In [74]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Numpy operations 

In [76]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [78]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [80]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr / arr

C:\Users\HP\AppData\Local\Temp\ipykernel_1148\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [82]:
1/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_1148\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [83]:
0/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_1148\4233011643.py:1: RuntimeWarning: invalid value encountered in divide
  0/arr


array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [85]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [86]:
np.log(arr)

C:\Users\HP\AppData\Local\Temp\ipykernel_1148\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [87]:
arr.std()

3.1622776601683795

In [88]:
arr.mean()

5.0

In [90]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
arr2d.sum()

300

In [93]:
# axis = 0 === perform operation across the rows
# axis = 1 === perform operation across the columns
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [94]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])